name: waste_classifier
description: A Flutter app for waste classification and recycling tips
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/ 